lincoln_park = Neighborhood.create(name: "Lincoln Park")
logan_square = Neighborhood.create(name: "Logan Square")
theloop = Neighborhood.create(name: "Loop")
river_north = Neighborhood.create(name: "River North")
south_loop = Neighborhood.create(name: "South Loop")
west_loop = Neighborhood.create(name: "West Loop")
wicker_park = Neighborhood.create(name: "Wicker Park")